import numpy as np

mydtype={'names':('gals','draco_gaia','draco','draco_js','draco_mw','carina_gaia','carina','carina_js','carina_mw','umi_gaia','umi','umi_js','umi_mw','leo1_gaia','leo1','leo1_js','leo1_mw','leo2_gaia','leo2','leo2_js','leo2_mw','sextans_gaia','sextans','sextans_js','sextans_mw','fornax_gaia','fornax','fornax_js','fornax_mw','sculptor_gaia','sculptor','sculptor_js','sculptor_mw',
   'tucana4_js', 'cetus2_js', 'cetus3_js', 'triangulum2_js', 'segue2_js', 'desj0225+0304_js', 'hydrus1_js', 'horologium1_js', 'horologium2_js', 'reticulum2_js', 'eridanus2_js', 'reticulum3_js', 'pictor1_js', 'columba1_js', 'pictor2_js',
 'carina2_js', 'carina3_js', 'uma2_js', 'leo_t_js', 'segue1_js', 'uma1_js', 'willman1_js', 'leo5_js', 'leo4_js','crater2_js',
 'virgo1_js', 'hydra2_js', 'coma_berenices_js', 'canes_venatici2_js', 'canes_venatici1_js', 'bootes2_js',
'bootes1_js','draco2_js', 'hercules_js', 'sagittarius_js', 'sagittarius2_js', 'indus2_js', 'grus2_js', 'pegasus3_js',
 'aquarius2_js', 'tucana2_js', 'grus1_js', 'pisces2_js','tucana5_js', 'phoenix2_js','tucana3_js'              
                 
                 
                 ),
                        'formats':(('U10',(8,4)),
                                   [('ra',float,393),('dec',float,393),\
                                                   ('ra_error',float,393),('dec_error',float,393),\
                                                   ('pmra',float,393),('pmdec',float,393),\
                                                   ('pmra_error',float,393),('pmdec_error',float,393),\
                                                   ('par',float,393),('par_error',float,393),\
                                                   ('par_over_error',float,393),('ra_dec_corr',float,393),\
                                                                         ('gflux',float,393),\
                                                   ('gmag',float,393),('bpflux',float,393),\
                                                   ('bpmag',float,393),('rpflux',float,393),\
                                                   ('rpmag',float,393),('bp_rp',float,393),\
                                                   ('bp_g',float,393),('g_rp',float,393)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(476,)),('dec',float,(476,)),\
                                                   ('Vhel',float,(476,)),('Vhel_error',float,(476,)),\
                                                   ('mem',float,(476,))],
                                   
                                   
                                   [('ra',float,717),('dec',float,717),\
                                                   ('ra_error',float,717),('dec_error',float,717),\
                                                   ('pmra',float,717),('pmdec',float,717),\
                                                   ('pmra_error',float,717),('pmdec_error',float,717),\
                                                   ('par',float,717),('par_error',float,717),\
                                                   ('par_over_error',float,717),('ra_dec_corr',float,717),\
                                                                         ('gflux',float,717),\
                                                   ('gmag',float,717),('bpflux',float,717),\
                                                   ('bpmag',float,717),('rpflux',float,717),\
                                                   ('rpmag',float,717),('bp_rp',float,717),\
                                                   ('bp_g',float,717),('g_rp',float,717)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(758,)),('dec',float,(758,)),\
                                                   ('Vhel',float,(758,)),('Vhel_error',float,(758,)),\
                                                   ('mem',float,(758,))],
                                   
                                   
                                   [('ra',float,309),('dec',float,309),\
                                                   ('ra_error',float,309),('dec_error',float,309),\
                                                   ('pmra',float,309),('pmdec',float,309),\
                                                   ('pmra_error',float,309),('pmdec_error',float,309),\
                                                   ('par',float,309),('par_error',float,309),\
                                                   ('par_over_error',float,309),('ra_dec_corr',float,309),\
                                                                         ('gflux',float,309),\
                                                   ('gmag',float,309),('bpflux',float,309),\
                                                   ('bpmag',float,309),('rpflux',float,309),\
                                                   ('rpmag',float,309),('bp_rp',float,309),\
                                                   ('bp_g',float,309),('g_rp',float,309)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(311,)),('dec',float,(311,)),\
                                                   ('Vhel',float,(311,)),('Vhel_error',float,(311,)),\
                                                   ('mem',float,(311,))],
                                   
                                   
                                   [('ra',float,464),('dec',float,464),\
                                                   ('ra_error',float,464),('dec_error',float,464),\
                                                   ('pmra',float,464),('pmdec',float,464),\
                                                   ('pmra_error',float,464),('pmdec_error',float,464),\
                                                   ('par',float,464),('par_error',float,464),\
                                                   ('par_over_error',float,464),('ra_dec_corr',float,464),\
                                                                         ('gflux',float,464),\
                                                   ('gmag',float,464),('bpflux',float,464),\
                                                   ('bpmag',float,464),('rpflux',float,464),\
                                                   ('rpmag',float,464),('bp_rp',float,464),\
                                                   ('bp_g',float,464),('g_rp',float,464)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(327,)),('dec',float,(327,)),\
                                                   ('Vhel',float,(327,)),('Vhel_error',float,(327,)),\
                                                   ('mem',float,(327,))],
                                   
                                   
                                   [('ra',float,192),('dec',float,192),\
                                                   ('ra_error',float,192),('dec_error',float,192),\
                                                   ('pmra',float,192),('pmdec',float,192),\
                                                   ('pmra_error',float,192),('pmdec_error',float,192),\
                                                   ('par',float,192),('par_error',float,192),\
                                                   ('par_over_error',float,192),('ra_dec_corr',float,192),\
                                                                         ('gflux',float,192),\
                                                   ('gmag',float,192),('bpflux',float,192),\
                                                   ('bpmag',float,192),('rpflux',float,192),\
                                                   ('rpmag',float,192),('bp_rp',float,192),\
                                                   ('bp_g',float,192),('g_rp',float,192)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(175,)),('dec',float,(175,)),\
                                                   ('Vhel',float,(175,)),('Vhel_error',float,(175,)),\
                                                   ('Fe_H',float,(175,)),('Fe_H_error',float,(175,)),\
                                                   ('mem',float,(175,))],
                                   
                                   
                                   [('ra',float,385),('dec',float,385),\
                                                   ('ra_error',float,385),('dec_error',float,385),\
                                                   ('pmra',float,385),('pmdec',float,385),\
                                                   ('pmra_error',float,385),('pmdec_error',float,385),\
                                                   ('par',float,385),('par_error',float,385),\
                                                   ('par_over_error',float,385),('ra_dec_corr',float,385),\
                                                                         ('gflux',float,385),\
                                                   ('gmag',float,385),('bpflux',float,385),\
                                                   ('bpmag',float,385),('rpflux',float,385),\
                                                   ('rpmag',float,385),('bp_rp',float,385),\
                                                   ('bp_g',float,385),('g_rp',float,385)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(424,)),('dec',float,(424,)),\
                                                   ('Vhel',float,(424,)),('Vhel_error',float,(424,)),\
                                                   ('mem',float,(424,))],
                                   
                                   
                                   [('ra',float,5603),('dec',float,5603),\
                                                   ('ra_error',float,5603),('dec_error',float,5603),\
                                                   ('pmra',float,5603),('pmdec',float,5603),\
                                                   ('pmra_error',float,5603),('pmdec_error',float,5603),\
                                                   ('par',float,5603),('par_error',float,5603),\
                                                   ('par_over_error',float,5603),('ra_dec_corr',float,5603),\
                                                                         ('gflux',float,5603),\
                                                   ('gmag',float,5603),('bpflux',float,5603),\
                                                   ('bpmag',float,5603),('rpflux',float,5603),\
                                                   ('rpmag',float,5603),('bp_rp',float,5603),\
                                                   ('bp_g',float,5603),('g_rp',float,5603)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(2409,)),('dec',float,(2409,)),\
                                                   ('Vhel',float,(2409,)),('Vhel_error',float,(2409,)),\
                                                   ('mem',float,(2409,))],
                                   
                                   
                                   [('ra',float,2360),('dec',float,2360),\
                                                   ('ra_error',float,2360),('dec_error',float,2360),\
                                                   ('pmra',float,2360),('pmdec',float,2360),\
                                                   ('pmra_error',float,2360),('pmdec_error',float,2360),\
                                                   ('par',float,2360),('par_error',float,2360),\
                                                   ('par_over_error',float,2360),('ra_dec_corr',float,2360),\
                                                                         ('gflux',float,2360),\
                                                   ('gmag',float,2360),('bpflux',float,2360),\
                                                   ('bpmag',float,2360),('rpflux',float,2360),\
                                                   ('rpmag',float,2360),('bp_rp',float,2360),\
                                                   ('bp_g',float,2360),('g_rp',float,2360)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(1349,)),('dec',float,(1349,)),\
                                                   ('Vhel',float,(1349,)),('Vhel_error',float,(1349,)),\
                                                   ('mem',float,(1349,))],
                                   
                                   
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                  [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))]
                                   
                                   
                                   
                                   
                                    )}