import numpy as np

mydtype={'names':('gals','draco_gaia','draco','draco_js','draco_ap','carina_gaia','carina','carina_js','carina_ap','umi_gaia','umi','umi_js','umi_ap','leo1_gaia','leo1','leo1_js','leo1_ap','leo2_gaia','leo2','leo2_js','leo2_ap','sextans_gaia','sextans','sextans_js','sextans_ap','fornax_gaia','fornax','fornax_js','fornax_ap','sculptor_gaia','sculptor','sculptor_js','sculptor_ap',
   'tucana4_js', 'cetus2_js', 'cetus3_js', 'triangulum2_js', 'segue2_js', 'desj0225+0304_js', 'hydrus1_js', 'horologium1_js', 'horologium2_js', 'reticulum2_js', 'eridanus2_js', 'reticulum3_js', 'pictor1_js', 'columba1_js', 'pictor2_js',
 'carina2_js', 'carina3_js', 'uma2_js', 'leo_t_js', 'segue1_js', 'uma1_js', 'willman1_js', 'leo5_js', 'leo4_js','crater2_js',
 'virgo1_js', 'hydra2_js', 'coma_berenices_js', 'canes_venatici2_js', 'canes_venatici1_js', 'bootes2_js',
'bootes1_js','draco2_js', 'hercules_js', 'sagittarius_js', 'sagittarius2_js', 'indus2_js', 'grus2_js', 'pegasus3_js',
 'aquarius2_js', 'tucana2_js', 'grus1_js', 'pisces2_js','tucana5_js', 'phoenix2_js','tucana3_js','smc','lmc'              
                 
                 
                 ),
                        'formats':(('U10',(8,4)),
                                   [('ra',float,422),('dec',float,422),\
                                                   ('ra_error',float,422),('dec_error',float,422),\
                                                   ('pmra',float,422),('pmdec',float,422),\
                                                   ('pmra_error',float,422),('pmdec_error',float,422),\
                                                   ('par',float,422),('par_error',float,422),\
                                                   ('par_over_error',float,422),('ra_dec_corr',float,422),\
                                                                         ('gflux',float,422),\
                                                   ('gmag',float,422),('bpflux',float,422),\
                                                   ('bpmag',float,422),('rpflux',float,422),\
                                                   ('rpmag',float,422),('bp_rp',float,422),\
                                                   ('bp_g',float,422),('g_rp',float,422)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(476,)),('dec',float,(476,)),\
                                                   ('Vhel',float,(476,)),('Vhel_error',float,(476,)),\
                                                   ('mem',float,(476,))],
                                   
                                   
                                   [('ra',float,976),('dec',float,976),\
                                                   ('ra_error',float,976),('dec_error',float,976),\
                                                   ('pmra',float,976),('pmdec',float,976),\
                                                   ('pmra_error',float,976),('pmdec_error',float,976),\
                                                   ('par',float,976),('par_error',float,976),\
                                                   ('par_over_error',float,976),('ra_dec_corr',float,976),\
                                                                         ('gflux',float,976),\
                                                   ('gmag',float,976),('bpflux',float,976),\
                                                   ('bpmag',float,976),('rpflux',float,976),\
                                                   ('rpmag',float,976),('bp_rp',float,976),\
                                                   ('bp_g',float,976),('g_rp',float,976)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(758,)),('dec',float,(758,)),\
                                                   ('Vhel',float,(758,)),('Vhel_error',float,(758,)),\
                                                   ('mem',float,(758,))],
                                   
                                   
                                   [('ra',float,323),('dec',float,323),\
                                                   ('ra_error',float,323),('dec_error',float,323),\
                                                   ('pmra',float,323),('pmdec',float,323),\
                                                   ('pmra_error',float,323),('pmdec_error',float,323),\
                                                   ('par',float,323),('par_error',float,323),\
                                                   ('par_over_error',float,323),('ra_dec_corr',float,323),\
                                                                         ('gflux',float,323),\
                                                   ('gmag',float,323),('bpflux',float,323),\
                                                   ('bpmag',float,323),('rpflux',float,323),\
                                                   ('rpmag',float,323),('bp_rp',float,323),\
                                                   ('bp_g',float,323),('g_rp',float,323)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(311,)),('dec',float,(311,)),\
                                                   ('Vhel',float,(311,)),('Vhel_error',float,(311,)),\
                                                   ('mem',float,(311,))],
                                   
                                   
                                   [('ra',float,907),('dec',float,907),\
                                                   ('ra_error',float,907),('dec_error',float,907),\
                                                   ('pmra',float,907),('pmdec',float,907),\
                                                   ('pmra_error',float,907),('pmdec_error',float,907),\
                                                   ('par',float,907),('par_error',float,907),\
                                                   ('par_over_error',float,907),('ra_dec_corr',float,907),\
                                                                         ('gflux',float,907),\
                                                   ('gmag',float,907),('bpflux',float,907),\
                                                   ('bpmag',float,907),('rpflux',float,907),\
                                                   ('rpmag',float,907),('bp_rp',float,907),\
                                                   ('bp_g',float,907),('g_rp',float,907)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(327,)),('dec',float,(327,)),\
                                                   ('Vhel',float,(327,)),('Vhel_error',float,(327,)),\
                                                   ('mem',float,(327,))],
                                   
                                   
                                   [('ra',float,405),('dec',float,405),\
                                                   ('ra_error',float,405),('dec_error',float,405),\
                                                   ('pmra',float,405),('pmdec',float,405),\
                                                   ('pmra_error',float,405),('pmdec_error',float,405),\
                                                   ('par',float,405),('par_error',float,405),\
                                                   ('par_over_error',float,405),('ra_dec_corr',float,405),\
                                                                         ('gflux',float,405),\
                                                   ('gmag',float,405),('bpflux',float,405),\
                                                   ('bpmag',float,405),('rpflux',float,405),\
                                                   ('rpmag',float,405),('bp_rp',float,405),\
                                                   ('bp_g',float,405),('g_rp',float,405)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(175,)),('dec',float,(175,)),\
                                                   ('Vhel',float,(175,)),('Vhel_error',float,(175,)),\
                                                   ('Fe_H',float,(175,)),('Fe_H_error',float,(175,)),\
                                                   ('mem',float,(175,))],
                                   
                                   
                                   [('ra',float,880),('dec',float,880),\
                                                   ('ra_error',float,880),('dec_error',float,880),\
                                                   ('pmra',float,880),('pmdec',float,880),\
                                                   ('pmra_error',float,880),('pmdec_error',float,880),\
                                                   ('par',float,880),('par_error',float,880),\
                                                   ('par_over_error',float,880),('ra_dec_corr',float,880),\
                                                                         ('gflux',float,880),\
                                                   ('gmag',float,880),('bpflux',float,880),\
                                                   ('bpmag',float,880),('rpflux',float,880),\
                                                   ('rpmag',float,880),('bp_rp',float,880),\
                                                   ('bp_g',float,880),('g_rp',float,880)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(424,)),('dec',float,(424,)),\
                                                   ('Vhel',float,(424,)),('Vhel_error',float,(424,)),\
                                                   ('mem',float,(424,))],
                                   
                                   
                                   [('ra',float,5603),('dec',float,5603),\
                                                   ('ra_error',float,5603),('dec_error',float,5603),\
                                                   ('pmra',float,5603),('pmdec',float,5603),\
                                                   ('pmra_error',float,5603),('pmdec_error',float,5603),\
                                                   ('par',float,5603),('par_error',float,5603),\
                                                   ('par_over_error',float,5603),('ra_dec_corr',float,5603),\
                                                                         ('gflux',float,5603),\
                                                   ('gmag',float,5603),('bpflux',float,5603),\
                                                   ('bpmag',float,5603),('rpflux',float,5603),\
                                                   ('rpmag',float,5603),('bp_rp',float,5603),\
                                                   ('bp_g',float,5603),('g_rp',float,5603)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(2409,)),('dec',float,(2409,)),\
                                                   ('Vhel',float,(2409,)),('Vhel_error',float,(2409,)),\
                                                   ('mem',float,(2409,))],
                                   
                                   
                                   [('ra',float,2906),('dec',float,2906),\
                                                   ('ra_error',float,2906),('dec_error',float,2906),\
                                                   ('pmra',float,2906),('pmdec',float,2906),\
                                                   ('pmra_error',float,2906),('pmdec_error',float,2906),\
                                                   ('par',float,2906),('par_error',float,2906),\
                                                   ('par_over_error',float,2906),('ra_dec_corr',float,2906),\
                                                                         ('gflux',float,2906),\
                                                   ('gmag',float,2906),('bpflux',float,2906),\
                                                   ('bpmag',float,2906),('rpflux',float,2906),\
                                                   ('rpmag',float,2906),('bp_rp',float,2906),\
                                                   ('bp_g',float,2906),('g_rp',float,2906)],
                                   [('center',float,(2,)),('center_ra',float,(1,)),('center_dec',float,(1,)),\
                                                   ('center_ra_error',float,(2,)),('center_dec_error',float,(2,)),\
                                                   ('distance',float,(1,)),('diameter',float,(1,)),\
                                                   ('avm',float,(1,)),('mass',float,(1,)),\
                                                   ('num',int,(1,)),('type','U10',(1,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('ra',float,(1349,)),('dec',float,(1349,)),\
                                                   ('Vhel',float,(1349,)),('Vhel_error',float,(1349,)),\
                                                   ('mem',float,(1349,))],
                                   
                                   
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                  [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   [('Mv',float,(1,)),('Mv_error',tuple,(2,)),\
                                                   ('r1_2',float,(1,)),('r1_2_error',tuple,(2,)),\
                                                   ('dist',float,(1,)),('dist_error',tuple,(2,)),\
                                                   ('Vhel',float,(1,)),('Vhel_error',tuple,(2,)),\
                                                   ('sigma',float,(1,)),('sigma_error',tuple,(2,)),\
                                                   ('Fe_H',float,(1,)),('Fe_H_error',tuple,(2,)),\
                                                   ('sigFe_H',float,(1,)),('sigFe_H_error',tuple,(2,))],
                                   #----- smc & lmc -----
                                   [('mass',float,(1,)),('distance',float,(1,))],
                                   [('mass',float,(1,)),('distance',float,(1,))]
                                   
                                   
                                   
                                    )}